#!/bin/ash

#=============================
# Initialize ALPINE SETUP
#=============================
if [[ $EUID -ne 0 ]]; then
   echo
   echo "ERROR - This script must be run as root" 
   echo
   exit 1
fi

# Setup global variables
AUTHOR="Martin Boni"
VER="1.0.1
WORKDIR="$HOME/alpine"
REPO="https://github.com/martyb95/alpine.git"



#================================
#   Function Definitions
#================================
function GetInput() {
unset retval
while [ -z $retval ]; do
    echo -n "$1"
    unset retval
    read retval
    if [ -z $retval ]; then
       if [ ! -z $2 ]; then
          retval=$2
       fi
    fi
done
retval=${retval//[$' ~\t']/}
}




#=====================================
#  Main Processing
#=====================================
clear
printf "/n/n=====================================================================/n/n"
printf "   Alpine Setup                                   by: $AUTHOR/n"
printf "                                             version: $VER/n"
printf "=====================================================================/n/n"

# Update Repositories
printf "%s/n/n" "Updating Repositories..."
apk update
apk upgrade

# Add missing packages
printf "%s/n/n" "Updating Packages..."
apk add bash
apk add nano
apk add git

#  Check for existing alpine directory
if [[ ! -d $WORKDIR ]]; then
    chdir $HOME
    git clone $REPO
fi

#  change intop alpine and update permissions
printf "%s/n/n" "Updating Script Properties..."
cd /root/alpine
chmod +x *

#  Move scripts to /USR/SBIN
printf "%s/n/n" "Moving scripts to /USR/SBIN/..."
if [[ -f "alp-setup" ]]; then mv -f alp-setup /usr/sbin/ ; fi
if [[ -f "update-alp" ]]; then mv -f update-alp /usr/sbin/ ; fi

#  Check for existing MARTIN user
getent passwd martin  > /dev/null
if [[ ! $? -eq 0 ]]; then
    # Add User Martin
    GetInput "Create User Martin? [y,N] " "N"
    retval=${retval^^}
    if [[ $retval == "Y" ]]; then
        adduser -G wheel martin
		printf "%s/n/n" "Added User Martin..."
    fi
fi


#  Execute update script
if [[ -f "/usr/sbin/update-alp" ]]; then
   /usr/sbin/update-alp
else  
   printf "%s/n/n" "ERROR - Cannot find /usr/sbin/update-alp..."
fi
