#!/bin/sh

#
#################################################################################
#  Setup Global Variables
#################################################################################
#
   clear

   # Program information
   GIT_REPO="https://github.com/CISOfy/lynis.git"
   MASTER_DIR="${HOME}/lynis"
   CURR_DIR="${PWD}"
   CMD=$1
   USR=$(whoami)

#
#################################################################################
#   Setup Lynis
#################################################################################
#
   # Check to verify that script is running as ROOT
   if [ ${USR} != "root" ]; then
     printf "\n\n==========================================================\n\n"
     printf "    Insufficient Priviledges....Please run as SU or ROOT\n"
     printf "\n\n==========================================================\n\n"
     exit 1
   fi

   # Check for blank first parameter
   if [ -z "$1" ]; then
      CMD="na"
   else
      CMD=$(echo "$1" | tr '[:upper:]' '[:lower:]')
   fi

   # Check for package update
   if [ ${CMD} = "update" ]; then
      if [ -d "${MASTER_DIR}" ]; then
         rm -rf ${MASTER_DIR}
      fi
      cd ${HOME}
      git clone ${GIT_REPO}
      cd ${CURR_DIR}
   else
      if [ ${CMD} = "na" ]; then
         printf "\n\nLynis\n"
         printf "\n==========================================================\n\n"
         printf "    lynis upgrade - will download the latest package\n"
         printf "                    from the GIT repository\n"
         printf "\n==========================================================\n\n"
      fi
      cd ${MASTER_DIR}
      ./lynis $1 $2 $3
      cd ${CURR_DIR}
   fi
